### ISSUE TITLE
Remember the last cursor position when a  prg file is closed and then re-opened

### ISSUE THREAD

**Issue by Ajitweb** [VFPX/Finder#1]
Hello Jim,

When I open the prg through Finder, the cursor is always at the top of the file.

When I do a modi comm <prg> in the command window - VFP seems to remember the last edited line number, and positions the cursor at that position.

Can Finder do the same ?

Regards,

Ajit

**Comment by Ajitweb** [comment]
From what I could find :

Finder is using PEM Editor to open the PRG file (in the editSourceX method of basecontextmenu class)
So far it is ok - and the opened PRG has the cursor position positioned correctly (where it was opened last)
But then in the next line - a call is made to Thor_Proc_SelectText which positions the cursor to the top of the PRG file (as the values of lnStartRange is zero)

Jim, can u please look at it.

Regards
Ajit

**Comment by Jimrnelson** [comment]
@Ajitweb 

Thanks for the suggestion.

I already have a fix in mind but have been having some difficulties releasing it.

**Comment by Jimrnelson** [comment]
@Ajitweb 

I am having problems getting the update of this out there so that you can download it.  Until I get it fixed, you can make the modification yourself:

`Modify Class basecontextmenu of Thor_Proc_Finder.vcx method EditSourceX`

..... and where's the replacement code (for the entire method)

```
Lparameters lcFileName, lcClass, lcMethod, lnStartRange, lnEndRange

* tools home page = http://vfpx.codeplex.com/wikipage?title=thor%20tools%20object
Local loTools As Pemeditor_tools Of 'c:\visual foxpro\programs\MyThor\thor\tools\apps\pem editor\source\peme_tools.vcx'

loTools = Execscript(_Screen.cThorDispatcher, 'Class= tools from pemeditor')

If Empty(m.lnEndRange)
	m.loTools.EditSourceX(m.lcFileName, m.lcClass, m.lcMethod)
Else
	m.loTools.EditSourceX(m.lcFileName, m.lcClass, m.lcMethod, m.lnStartRange, m.lnEndRange)
	If Vartype(m.lnStartRange) = 'N' And 'PRG' = Upper(Justext(m.lcFileName))
		Execscript(_Screen.cThorDispatcher, 'Thor_Proc_SelectText', m.lnStartRange, m.lnEndRange)
	Endif
Endif

Return .T.

```

**Comment by Ajitweb** [comment]
Thanks Jim.
Done and then copied the Thor_Proc_Finder.vcx & Thor_Proc_Finder.vct to my other dev machine's
 . . . . . .\Thor\Thor\Tools\Procs directory.

Working as expected
Thanks once again.
